os: linux
dist: focal
language: python
jobs:
 include: 
 - name: "test" # existing functionality
   script: # existing functionality
    - npm -v
 - name: "sbom"
   script: # existing functionality
     - cd python
     - npm install
   addons:
     sbom:
       on:
         branch: 'main'
         pr: true
       # condition: true
       run_phase: "after_failure" # 
       output_format: "spdx-json" # 
       output_dir: "/test" # 
       input_dir: "/node" #
